import {readInstalledSkill} from "../src/marketplace/search.ts";
import {it,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,chmodSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {createAgentImports} from '../src/imports/manager.ts';
import {createImportSync} from '../src/imports/sync.ts';
import {readBotContext,writeBotContext,getBot,updateBot,listBots} from '../src/bots/manager.ts';
import {setProvider} from '../src/auth/store.ts';
import {eventsAfter,appendEvent,bus} from '../src/events/log.ts';
import {listGroups} from '../src/chat/session.ts';
let root:string,hermes:string,grok:string;const prior=process.env.LINUBOT_DATA;
const file=(path:string,value:string)=>{mkdirSync(join(path,'..'),{recursive:true});writeFileSync(path,value);};
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'linubot-sync-'));hermes=join(root,'hermes');grok=join(root,'grok');process.env.LINUBOT_DATA=join(root,'target');setProvider({kind:'openai-compat',baseUrl:'https://fixture.example/v1',model:'fixture',auth:'none'});file(join(hermes,'SOUL.md'),'Research carefully.');file(join(hermes,'MEMORY.md'),'Original source memory');file(join(hermes,'skills/check/SKILL.md'),'---\nname: check\ndescription: Verify facts\n---\nOriginal procedure');file(join(hermes,'skills/check/guide.txt'),'Original guide');const db=new DatabaseSync(join(hermes,'state.db'));db.exec("CREATE TABLE sessions (id TEXT,title TEXT,model TEXT,started_at REAL);CREATE TABLE messages(id INTEGER,session_id TEXT,role TEXT,content TEXT,timestamp REAL);INSERT INTO sessions VALUES ('session','Original chat','fixture',100);INSERT INTO messages VALUES (1,'session','user','Original request',101),(2,'session','assistant','Original reply',102)");db.close();});
afterEach(()=>{rmSync(root,{recursive:true,force:true});if(prior===undefined)delete process.env.LINUBOT_DATA;else process.env.LINUBOT_DATA=prior;});
function imported(){const imports=createAgentImports({hermes,grok});const source=imports.discover().candidates.find(source=>source.source==='hermes')!;return imports.commit(imports.preview({sourceId:source.id}).id);}
function newer(){const db=new DatabaseSync(join(hermes,'state.db'));db.exec("INSERT INTO messages VALUES (3,'session','assistant','New source reply',103)");db.close();file(join(hermes,'MEMORY.md'),'New source memory');file(join(hermes,'skills/check/SKILL.md'),'---\nname: check\ndescription: Verify facts\n---\nUpdated procedure');file(join(hermes,'skills/check/guide.txt'),'Updated guide');}
it('pulls new history and changed knowledge once while preserving native profile choices',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`;updateBot(name,{goal:'My local goal'});newer();const sync=createImportSync({hermes,grok});const preview=sync.preview(scope);assert.equal(preview.messages,1);assert.equal(preview.changes.length,2);const result=sync.commit(preview.id) as {messages:number;updated:number};assert.equal(result.messages,1);assert.equal(result.updated,2);assert.deepEqual(sync.commit(preview.id),result);assert.equal(readBotContext(name).includes('New source memory'),true);assert.equal(getBot(name)?.goal,'My local goal');assert.equal(listBots().length,1);assert.equal(readFileSync(join(process.env.LINUBOT_DATA!,'skills',first.skills[0],'guide.txt'),'utf8'),'Updated guide');const again=createImportSync({hermes,grok}).preview(scope);assert.equal(again.messages,0);assert.deepEqual(again.changes,[]);assert.equal(eventsAfter(scope,0).filter(event=>event.text==='New source reply').length,1);});
it('keeps local-only changes and asks before replacing changes made on both sides',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`;writeBotContext(name,'My local knowledge');const sync=createImportSync({hermes,grok});let preview=sync.preview(scope);assert.equal(preview.changes.length,0);sync.commit(preview.id);assert.equal(readBotContext(name),'My local knowledge');file(join(hermes,'MEMORY.md'),'Changed upstream knowledge');preview=sync.preview(scope);assert.equal(preview.changes[0].status,'conflict');const kept=sync.commit(preview.id) as {conflicts:number};assert.equal(kept.conflicts,1);assert.equal(readBotContext(name),'My local knowledge');preview=sync.preview(scope);sync.commit(preview.id,true);assert.match(readBotContext(name),/Changed upstream/);});
it('does not duplicate legacy imported messages or overwrite untracked legacy knowledge',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`;const metaPath=join(process.env.LINUBOT_DATA!,'profiles',name,'import.json'),meta=JSON.parse(readFileSync(metaPath,'utf8'));delete meta.baseline;writeFileSync(metaPath,JSON.stringify(meta));const feed=join(process.env.LINUBOT_DATA!,`feed-bot_${name}.jsonl`);writeFileSync(feed,readFileSync(feed,'utf8').trim().split('\n').map(line=>{const event=JSON.parse(line);delete event.importKey;return JSON.stringify(event);}).join('\n')+'\n');newer();const sync=createImportSync({hermes,grok}),preview=sync.preview(scope);assert.equal(preview.messages,1);assert.ok(preview.changes.every(change=>change.status==='conflict'));sync.commit(preview.id);assert.match(readBotContext(name),/Original source/);assert.equal(sync.preview(scope).messages,0);});
it('rejects stale destination state and active work before any sync mutation',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`;newer();const sync=createImportSync({hermes,grok}),preview=sync.preview(scope);appendEvent(scope,{kind:'message',from:'user',text:'New local message'});assert.throws(()=>sync.commit(preview.id),/changed after/);assert.match(readBotContext(name),/Original source/);const busy=createImportSync({hermes,grok},()=>true),blocked=busy.preview(scope);assert.throws(()=>busy.commit(blocked.id),/Finish active work/);assert.equal(eventsAfter(scope,0).some(event=>event.text==='New source reply'),false);});
it('rolls back failed writes before publishing history and permits an idempotent retry',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`;newer();const sync=createImportSync({hermes,grok}),preview=sync.preview(scope);const receiptRoot=join(process.env.LINUBOT_DATA!,'import-sync');mkdirSync(receiptRoot,{mode:0o500});let published=0;const listener=()=>published++;bus.on('event',listener);try{assert.throws(()=>sync.commit(preview.id),/EACCES/);assert.match(readBotContext(name),/Original source/);assert.equal(readFileSync(join(process.env.LINUBOT_DATA!,'skills',first.skills[0],'guide.txt'),'utf8'),'Original guide');assert.equal(published,0);chmodSync(receiptRoot,0o700);sync.commit(preview.id);assert.equal(published,1);assert.equal(sync.preview(scope).messages,0);}finally{chmodSync(receiptRoot,0o700);bus.off('event',listener);}});
function encoded(value:string){let bits=0,buffer=0,output='';for(const byte of Buffer.from(value)){buffer=(buffer<<8)|byte;bits+=8;while(bits>=5){bits-=5;output+='abcdefghijklmnopqrstuvwxyz234567'[(buffer>>bits)&31];}}if(bits)output+='abcdefghijklmnopqrstuvwxyz234567'[(buffer<<(5-bits))&31];return output;}
it('syncs newer Grok group history with the correct speaker and stable membership',()=>{const account='sand.client.slice.account.sync',blob=(key:string,value:unknown,schemaVersion=1)=>file(join(grok,encoded(key)+'.blob'),JSON.stringify({schemaVersion,value}));blob(account+'.roster.last-roster',{rows:[{id:'a',name:'Pip'},{id:'b',name:'Fern'},{id:'g',name:'Team',isGroup:true,memberIds:['a','b']}]},3);const entries=[{id:'one',kind:'message',role:'user',content:'Old group request',timestampMs:1700000000000}];blob(account+'.transcript.replicas.g',{entries});const imports=createAgentImports({hermes,grok}),group=imports.discover().candidates.find(source=>source.kind==='group')!;const result=imports.commit(imports.preview({sourceId:group.id}).id),members=[...listGroups()[0].members];blob(account+'.transcript.replicas.g',{entries:[...entries,{id:'two',kind:'send-message',message:{type:'text',content:'New group reply'},author:{id:'b'},timestampMs:1700000001000}]});const sync=createImportSync({hermes,grok}),preview=sync.preview(result.scope);assert.equal(preview.messages,1);sync.commit(preview.id);assert.equal(eventsAfter(result.scope,0).find(event=>event.text==='New group reply')?.from,'Fern');assert.deepEqual(listGroups()[0].members,members);assert.equal(sync.preview(result.scope).messages,0);});

it('adds new skills once and preserves an owner choice to detach them',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`;file(join(hermes,'skills/new/SKILL.md'),'---\nname: new\ndescription: New source procedure\n---\nFirst version');const sync=createImportSync({hermes,grok}),preview=sync.preview(scope);assert.equal(preview.changes.filter(change=>change.kind==='skill'&&change.status==='new').length,1);sync.commit(preview.id);const added=getBot(name)!.skills.find(skill=>!first.skills.includes(skill))!;assert.equal(readInstalledSkill(added)?.status,'approved');updateBot(name,{skills:first.skills});file(join(hermes,'skills/new/SKILL.md'),'---\nname: new\ndescription: New source procedure\n---\nSecond version');sync.commit(sync.preview(scope).id);assert.deepEqual(getBot(name)!.skills,first.skills);assert.equal(readInstalledSkill(added)?.body,'Second version');});
it('preserves edited supporting files unless the owner explicitly replaces the conflict',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`,guide=join(process.env.LINUBOT_DATA!,'skills',first.skills[0],'guide.txt');writeFileSync(guide,'My local guide');file(join(hermes,'skills/check/guide.txt'),'New source guide');const sync=createImportSync({hermes,grok});let preview=sync.preview(scope);assert.equal(preview.changes.find(change=>change.kind==='skill')?.status,'conflict');sync.commit(preview.id);assert.equal(readFileSync(guide,'utf8'),'My local guide');preview=sync.preview(scope);sync.commit(preview.id,true);assert.equal(readFileSync(guide,'utf8'),'New source guide');});
it('applies the checked snapshot even if source files change before confirmation',()=>{const first=imported(),name=first.bots[0],scope=`bot:${name}`;file(join(hermes,'MEMORY.md'),'Reviewed memory');const sync=createImportSync({hermes,grok}),preview=sync.preview(scope);file(join(hermes,'MEMORY.md'),'Unreviewed later memory');sync.commit(preview.id);assert.match(readBotContext(name),/Reviewed memory/);assert.doesNotMatch(readBotContext(name),/Unreviewed/);assert.equal(sync.preview(scope).changes.find(change=>change.kind==='memory')?.status,'update');});
